# Source the .profile in sh emulation mode
[[ -e ~/.profile ]] && emulate sh -c 'source ~/.profile'

# Set up zsh completion
autoload -Uz compinit
compinit

zstyle ':completion:*:descriptions' format '%U%B%d%b%u'
zstyle ':completion:*:warnings' format '%BSorry, no matches for: %d%b'

# Load prompt
source ~/.zsh/config/prompt.zsh

alias ls='ls -l'
alias ot='popd'
alias to='pushd'

# Use Vi mode
bindkey -v

bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
bindkey '^r' history-incremental-search-backward

export KEYTIMEOUT=1

# Set patform depending on OS
platform='unknown'
if [[ $OSTYPE =~ darwin* ]]; then
    platform='darwin'
elif [[ $OSTYPE =~ linux* ]]; then
   platform='linux'
fi

# Add the ~ bin
export PATH=$HOME/bin:$PATH

# Add Homebrew path
if [[ $platform == 'darwin' ]] && (( $+commands[brew] )) ; then
   export PATH=/usr/local/bin:$PATH
fi

# Set JAVA_HOME
export JAVA_HOME=$(/usr/libexec/java_home -v1.8)

# Initialize nvm
if [[ $platform == 'darwin' ]] ; then
    export NVM_DIR=~/.nvm
    source $(brew --prefix nvm)/nvm.sh
fi

# Initialize rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# Configure Lynx
if [ -e "$HOME/.lynx.lss" ] ; then
    export LYNX_LSS="$HOME/.lynx.lss"
fi

if [ -e "$HOME/.lynx.cfg" ] ; then
    export LYNX_CFG="$HOME/.lynx.cfg"
fi

